#!/usr/bin/env bash

set -e
set -u

TMPDIR=${TMPDIR:=/tmp}
test -d $TMPDIR

AP_BRANCH="master"
AP_FILES=.
AP_CMD="tools/patchnewgtlds"

AP_TARGET_REPO="publicsuffix/list"
REPO_URL="https://github.com/${AP_TARGET_REPO}.git"
FORK_URL="https://${GH_USER}:${GH_TOKEN}@github.com/tld-update-bot/list.git"
CREATE_PR_URL="https://api.github.com/repos/${AP_TARGET_REPO}/pulls"

DATE="$(date -u +%Y-%m-%d)"
SAFE_DATE="$(date -u +%Y-%m-%d-%H-%M-%S)"
BRANCH="autopull/${AP_BRANCH}/${SAFE_DATE}"
DIR="${TMPDIR}/autopull/${SAFE_DATE}"

AP_REPO_DIR="${DIR}/${AP_TARGET_REPO}"
LOG="${DIR}/cmd.log"
JSON="${DIR}/pull-request.json"

echo "Work dir:   $DIR"
echo "Repo dir:   $AP_REPO_DIR"

mkdir -p $DIR
git clone $REPO_URL $AP_REPO_DIR
(
cd $AP_REPO_DIR
git checkout $AP_BRANCH
git checkout -q -b $BRANCH
git remote add fork $FORK_URL

$AP_CMD

if  git diff --numstat 2>/dev/null | tr -d '\n' | grep -q -P "1\t1\tpublic_suffix_list.dat";
then
  echo "Nothing new to commit. $AP_BRANCH is current."
  exit 0
fi

git add --all $AP_FILES
echo -e "gTLD autopull: ${DATE}" | git commit -F -
git push fork $BRANCH:$BRANCH

PR=$(cat <<EOF
{
  "title": "gTLD autopull: $DATE",
  "base": "$AP_BRANCH",
  "head": "$GH_USER:$BRANCH",
  "body": ":robot: gTLD \`public_suffix_list.dat\` data updates for $DATE."
}
EOF
)

curl -sS -i \
--header "Authorization: token ${GH_TOKEN}" \
--data "${PR}" \
--request POST ${CREATE_PR_URL} > $JSON

grep -q "201 Created" $JSON || (cat $JSON && exit 1)
API_URL=$(grep -A1 '"self": {' $JSON | grep href | cut -f 2- -d ':' | cut -f 2 -d '"')
PULL_ID=$(echo $API_URL | cut -f 8- -d / )
PR_URL="https://github.com/${AP_TARGET_REPO}/pull/${PULL_ID}"
echo "Created pull request $PULL_ID: $PR_URL"
)
